# Generated by Django 2.2.3 on 2019-07-29 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('animal', models.CharField(max_length=150)),
                ('breed', models.CharField(blank=True, max_length=150)),
                ('weight', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('profile_image', models.ImageField(upload_to='media/')),
                ('about_me', models.TextField(help_text='Tell us about your pet (likes, dislikes, fun quirks, and more).', max_length=2000)),
                ('vet_info', models.TextField(help_text="Enter your pet's vet info (name, address, and contact number).", max_length=2000)),
                ('emergency_contact', models.TextField(help_text='Someone other than yourself in the case of emergencies (enter their name, number, and email).', max_length=2000)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_owner', to=settings.AUTH_USER_MODEL)),
                ('sitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('assigned_pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_phone', models.TextField(blank=True, max_length=9)),
                ('mobile_phone', models.TextField(blank=True, max_length=9)),
                ('work_phone', models.TextField(blank=True, max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Critical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('due_date', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('assigned_pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pet')),
            ],
        ),
    ]
