# Generated by Django 2.2.3 on 2019-07-29 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='about_me',
            field=models.TextField(blank=True, help_text='Tell us about your pet (likes, dislikes, fun quirks, and more).', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='emergency_contact',
            field=models.TextField(blank=True, help_text='Someone other than yourself in the case of emergencies (enter their name, number, and email).', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_sitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='vet_info',
            field=models.TextField(blank=True, help_text="Enter your pet's vet info (name, address, and contact number).", max_length=2000, null=True),
        ),
    ]
