# Generated by Django 2.2.3 on 2019-07-29 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20190729_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='assigned_sitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
