# Generated by Django 2.2.3 on 2019-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190729_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='pet_pictures'),
        ),
    ]
