# Generated by Django 2.2.3 on 2019-07-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190730_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='about_me',
            new_name='about_Me',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='emergency_contact',
            new_name='emergency_Contact',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='profile_image',
            new_name='profile_Image',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='vet_info',
            new_name='vet_Info',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='weight',
            new_name='weight_in_lbs',
        ),
        migrations.AddField(
            model_name='pet',
            name='color_and_Markings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
