# Generated by Django 2.2.3 on 2019-07-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190730_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight_in_lbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
