# Generated by Django 2.2.4 on 2019-08-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190731_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='visits',
            new_name='visit',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='due_date_on',
            field=models.DateField(),
        ),
    ]
