# Generated by Django 2.2.3 on 2019-07-31 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190731_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='checklist_id',
            new_name='checklist',
        ),
    ]
