# Generated by Django 2.2.3 on 2019-07-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190731_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='due_date_on',
            field=models.DateField(),
        ),
    ]
